from trainer_gan import GANModelTraining
from utils import*
from torch.utils.data import random_split, ConcatDataset
from trainer_cnn import CNNModelTraining
import torchvision.transforms as T
from config_cnn import*
from imageprocessing import get_transformations, get_stats, ds_mean, ds_std
from torchvision.datasets import ImageFolder
from torchvision import datasets, models, transforms


class Main:

    def runmain(self):
        datetimestr = time.strftime('%Y%m%d-%H%M') # Every file generated by running made will have filename_2023MMDD-HHmm.extension as the format
        print('The current Date-Time group is: '+ datetimestr)

        # # Set random seed for either reproducibility or randomness
        seed_value = 42
        random_gen = torch.manual_seed(seed_value) # results seem constant per run
        # random_gen = random.seed(seed_value) # results seem random per run


        # # # Optional section 1 for trans_20 in imageprocessing.py if you prefer to use mean and standard deviation calculated
        # # # for the specific dataset being used.
        # # # dataset = datasets.MNIST(root="data/", transform=T.Compose([T.ToTensor()]))
        # # dataset = ImageFolder(dataroot, transform=T.Compose([T.ToTensor()]))
        # # loader = DataLoader(dataset, batch_size=1, shuffle=False,)
        # # mean, stan = get_stats(loader)
        # # for elem in mean:
        # #     ds_mean.append(elem)
        # # for elem in stan:
        # #     ds_std.append(elem)
        #
        # # Aggregate image transformations - these are list indices; imageprocessing.py has the list if you need more
        composelist_g = get_transformations([15, 16, 17])  # Note if using idx 19 (trans_20) , uncomment the optional section 1 above
        # Data to dataset object
        # dataroot = "/path_to_root_of_image_dir"
        # gan_dataset = ImageFolder(dataroot, transform=T.Compose(composelist_g.transforms))
        gan_dataset = datasets.MNIST(root="data/", transform=T.Compose(composelist_g.transforms))

        # # Optional section 2 When you only want to generate certain classes uncomment this and fill in the list accordingly - of course you must know your class indices
        # targets = [4, 5, 6, 7]
        # gan_dataset = select_classes(gan_dataset, targets)

        class_list = gan_dataset.classes


        # Configure data subset sizes and create them
        test_percentage = 0.1 # (dataset_size - NUM_TRAIN_SAMPLES) / dataset_size

        # If you need training and test sets run stratify once
        gan_train, gan_test = stratified_split(gan_dataset, test_percentage)

        # # # If you need training, test, AND validation sets, split the test set
        # gan_val, gan_test = random_split(gan_test, [0.5, 0.5], generator=random_gen)

        # Train the GAN model
        GANModelTraining().train_gan_model(gan_train, class_list)

        # # Note: random_split can be used with:
        # # torch.datasets
        # # torchvision.datasets import ImageFolder (for local folders)
        # # Note: The original CNN project used in this project has two different datasubsets in a dictionary with keys
        # # 'train' and 'val'
        # # Note: sklean train_test_split is also very useful
        # print('The GAN is done...')
        # halt()
        ########CNN PORTION

        # # Aggregate image transformations - these are list indices; imageprocessing.py has the list if you need more
        # Note if using idx 19 (trans_20) , uncomment the optional section 1 above
        # Note idx 0 with channels set to 3 is a must for retraining with augments from the GAN
        composelist_c = get_transformations([0, 15, 16, 17])
        # Data to dataset object
        cnn_dataset = datasets.MNIST(root="data/", transform=T.Compose(composelist_c.transforms))

        # Configure data subset sizes and create them
        dataset_size = len(cnn_dataset)

        test_percentage = (dataset_size - NUM_TRAIN_SAMPLES) / dataset_size

        # If you need training and test sets run stratify once
        cnn_train, cnn_test = stratified_split(cnn_dataset, test_percentage)

        # # If you need training, test, AND validation sets, split the test set
        cnn_val, cnn_test = random_split(cnn_test, [0.9, 0.1], generator=random_gen)

        # Create a dictionary from two subsets of the data
        cnn_dataset_dict= {'train':cnn_train, 'val':cnn_val}
        dataset_sizes = {x: len(cnn_dataset_dict[x]) for x in ['train', 'val']}

        print(dataset_sizes)

        # # Create a dictionary from three subsets of the data
        # cnn_dataset_dict= {'train':cnn_train, 'test':cnn_test, 'val':cnn_val}
        # dataset_sizes = {x: len(cnn_dataset_dict[x]) for x in ['train', 'test', 'val']}

        #  Create a list of classes
        class_names = cnn_dataset.classes

        # Train the CNN model
        CNNModelTraining().train_cnn_model(cnn_dataset_dict, dataset_sizes, class_names)
        print("First training done...")

        # Augment the training set
        gen_data_root = './aug_data'
        gen_dataset = ImageFolder(gen_data_root, transforms.Compose(composelist_c.transforms))
        aug_dataset = ConcatDataset([cnn_train, gen_dataset])

        # Create a new dictionary from two subsets of the data  ---> _a is for augmented (train ds)
        cnn_dataset_dict_a= {'train':aug_dataset, 'val':cnn_val}
        dataset_sizes_a = {x: len(cnn_dataset_dict_a[x]) for x in ['train', 'val']}

        print(dataset_sizes_a)

        # Retrain the CNN model
        CNNModelTraining().train_cnn_model(cnn_dataset_dict_a, dataset_sizes_a, class_names)
        print("Second training done...")

        # # Activate to print the state dictionary of the model returned from trainer_cnn
        # print_dict(cnn_model_trained)

        # Load the trained model and train again with GAN augmented dataset

        # # Save the model returned from trainer_cnn
        # filepath = './models/cnn_model_save'+ datetimestr
        # torch.save(cnn_model_trained, filepath )

if __name__ == '__main__':
    doo = Main()
    doo.runmain()
